/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RuleService } from "../rule.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RuleCreateInput } from "./RuleCreateInput";
import { Rule } from "./Rule";
import { RuleFindManyArgs } from "./RuleFindManyArgs";
import { RuleWhereUniqueInput } from "./RuleWhereUniqueInput";
import { RuleUpdateInput } from "./RuleUpdateInput";
import { CouponFindManyArgs } from "../../coupon/base/CouponFindManyArgs";
import { Coupon } from "../../coupon/base/Coupon";
import { CouponWhereUniqueInput } from "../../coupon/base/CouponWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RuleControllerBase {
  constructor(
    protected readonly service: RuleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Rule })
  @nestAccessControl.UseRoles({
    resource: "Rule",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRule(@common.Body() data: RuleCreateInput): Promise<Rule> {
    return await this.service.createRule({
      data: data,
      select: {
        createdAt: true,
        discount: true,
        discountType: true,
        endTo: true,
        id: true,
        startFrom: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Rule] })
  @ApiNestedQuery(RuleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Rule",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rules(@common.Req() request: Request): Promise<Rule[]> {
    const args = plainToClass(RuleFindManyArgs, request.query);
    return this.service.rules({
      ...args,
      select: {
        createdAt: true,
        discount: true,
        discountType: true,
        endTo: true,
        id: true,
        startFrom: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Rule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Rule",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rule(
    @common.Param() params: RuleWhereUniqueInput
  ): Promise<Rule | null> {
    const result = await this.service.rule({
      where: params,
      select: {
        createdAt: true,
        discount: true,
        discountType: true,
        endTo: true,
        id: true,
        startFrom: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Rule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Rule",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRule(
    @common.Param() params: RuleWhereUniqueInput,
    @common.Body() data: RuleUpdateInput
  ): Promise<Rule | null> {
    try {
      return await this.service.updateRule({
        where: params,
        data: data,
        select: {
          createdAt: true,
          discount: true,
          discountType: true,
          endTo: true,
          id: true,
          startFrom: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Rule })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Rule",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRule(
    @common.Param() params: RuleWhereUniqueInput
  ): Promise<Rule | null> {
    try {
      return await this.service.deleteRule({
        where: params,
        select: {
          createdAt: true,
          discount: true,
          discountType: true,
          endTo: true,
          id: true,
          startFrom: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/coupons")
  @ApiNestedQuery(CouponFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Coupon",
    action: "read",
    possession: "any",
  })
  async findCoupons(
    @common.Req() request: Request,
    @common.Param() params: RuleWhereUniqueInput
  ): Promise<Coupon[]> {
    const query = plainToClass(CouponFindManyArgs, request.query);
    const results = await this.service.findCoupons(params.id, {
      ...query,
      select: {
        couponCode: true,
        createdAt: true,
        id: true,

        rule: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/coupons")
  @nestAccessControl.UseRoles({
    resource: "Rule",
    action: "update",
    possession: "any",
  })
  async connectCoupons(
    @common.Param() params: RuleWhereUniqueInput,
    @common.Body() body: CouponWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      coupons: {
        connect: body,
      },
    };
    await this.service.updateRule({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/coupons")
  @nestAccessControl.UseRoles({
    resource: "Rule",
    action: "update",
    possession: "any",
  })
  async updateCoupons(
    @common.Param() params: RuleWhereUniqueInput,
    @common.Body() body: CouponWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      coupons: {
        set: body,
      },
    };
    await this.service.updateRule({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/coupons")
  @nestAccessControl.UseRoles({
    resource: "Rule",
    action: "update",
    possession: "any",
  })
  async disconnectCoupons(
    @common.Param() params: RuleWhereUniqueInput,
    @common.Body() body: CouponWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      coupons: {
        disconnect: body,
      },
    };
    await this.service.updateRule({
      where: params,
      data,
      select: { id: true },
    });
  }
}
